---
title: "Plot in R-HW04"
author: "許循閒"
date: "2019年3月25日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r cars}
plot(etf4_returns_xts, xaxt='n')
axis(1, index(etf4_returns_xts), format(index(etf4_returns_xts), "%Y/%m"))

etf4_ret.df1<-fortify(etf4_returns_xts)
head(etf4_ret.df1)
plot(etf4_ret.df1$`0050`, etf4_ret.df1$`00646`, pch=20,
     col = 'darkred', main = '0050 vs. 00646 monthly returns',
     xlab = '0050', ylab = '00646 S&P500')
```
#畫出etf4_returns_xts的圖
xaxt='n'-讓x軸消失
axis 1-控制下方的X軸
fortify 的意思

```{r cars}
library(tidyverse)
library(ggplot2)
library(lubridate)
etf4_ret.df2 <- cbind(etf4_ret.df1, month=month(index(etf4_returns_xts)), 
                      year=year(index(etf4_returns_xts)))

ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, color = month))

ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, size = month))

ggplot(data = etf4_ret.df2) +
  geom_point(mapping = aes(x = etf4_ret.df2$`0050`, y = etf4_ret.df2$`0056`, alpha = month))

etf4_ret
etf4_ret.tmp<-data.frame(date = index(etf4_returns_xts), etf4_ret)
head(etf4_ret.tmp)
```


```{r cars}
plot(etf4_ret.tmp$X0050, etf4_ret.tmp$X0056)

ggplot(etf4_ret.tmp) +
  geom_point(mapping = aes(x = etf4_ret.tmp$X0050, y = etf4_ret.tmp$X0056))


etf4_ret.df<-fortify(etf4_returns_xts, melt=TRUE)
head(etf4_ret.df)

p<-ggplot(etf4_ret.df, aes(x = Index, y = Value))+
  geom_line(aes(color = Series), size = 1)
p + scale_x_date(date_labels = "%Y/%m")
p
```


```{r cars}
q<-etf4_ret.df %>%
  ggplot(aes(x =Value, fill = Series)) +
  geom_histogram(alpha = 0.45, binwidth = .005) +
  ggtitle("Monthly Returns")
q + facet_wrap(~Series)+ theme_update(plot.title = element_text(hjust = 0.5))

q
```


```{r cars}
etf4_ret.df %>%
  ggplot(aes(x = Value, colour = Series)) +
  geom_density(alpha = 1) +
  ggtitle("Monthly Returns Density Since 2016") +
  xlab("monthly returns") +
  ylab("distribution") +
  theme_update(plot.title = element_text(hjust = 0.5))
```


```{r cars}
etf4_ret.df %>%
  ggplot(aes(x = Value)) +
  geom_density(aes(color = Series), alpha = 1) +
  geom_histogram(aes(fill = Series), alpha = 0.45, binwidth = .01) +
  guides(fill = FALSE) +
  facet_wrap(~Series) +
  ggtitle("Monthly Returns Since 2016") +
  xlab("monthly returns") +
  ylab("distribution") +
  theme_update(plot.title = element_text(hjust = 0.5))
```


```{r cars}
library(plotly)
p1 = plot_ly(etf4_ret.tmp, x= ~date, y= ~X0050, name = "0050", type = "scatter",mode = "lines") %>% 
  add_trace(y=~X0056, name = '0056',mode = 'lines+markers')%>%
  layout(xaxis = list(title = 'year'), yaxis = list(title= 'monthly returns'))
p1
```







